language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev" # 3.6 development branch
  - "nightly"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install .
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ordereddict unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install cryptography==0.9; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy3 ]]; then pip install cryptography==0.9; fi
  - pip install pyOpenSSL
# command to run tests
script: nosetests
