language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev" # 3.6 development branch
  - "nightly"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install codecov
  - pip install coverage
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install ordereddict unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy'* ]]; then travis_retry pip install cryptography==0.9 pyOpenSSL==0.15; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install pyOpenSSL; fi
  - pip install .
# command to run tests
script: nosetests --with-coverage
after_success:
  - codecov